name: Espelhar Repositorio

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # <--- A MÁGICA ESTÁ AQUI

      - name: Empurrar para o Destino
        env:
          DEST_REPO: github.com/davidvieira02/Autoblog-Mirror.git
          USER_TOKEN: ${{ secrets.DESTINO_TOKEN }}
        run: |
          git remote add mirror https://${USER_TOKEN}@${DEST_REPO}
          git push mirror main --force
